"use client";

import { Plus } from "lucide-react";
import { useState } from "react";

const QuestionList = [
  {
    q: 'What is an AI Headshot Generator?',
    a: 'An AI Headshot Generator is a tool that uses artificial intelligence to create professional-looking headshots. It typically processes a users photo and enhances it to produce a polished, studio-quality image suitable for various professional uses.'
  },
  {
    q: 'How does the AI Headshot Generator work?',
    a: 'The AI Headshot Generator works by analyzing the uploaded photo and applying advanced algorithms to adjust lighting, remove imperfections, and enhance facial features. It can also crop and resize the image to meet professional standards, ensuring a high-quality headshot.'
  },
  {
    q: 'Is the AI Headshot Generator really free for first-time users?',
    a: 'Yes, many AI Headshot Generators offer their services for free to first-time users. This allows new users to experience the quality and convenience of the tool without any initial cost. However, there may be limitations on the number of photos or features available in the free version.'
  },
  {
    q: 'What kind of photos can be used with the AI Headshot Generator?',
    a: 'The AI Headshot Generator can work with a variety of photo formats, but it typically performs best with clear, well-lit images where the subjects face is clearly visible. Photos taken with a plain background and minimal distractions tend to yield the best results.'
  },
  {
    q: 'Can I use the generated headshot for professional purposes?',
    a: 'Yes, the headshots generated by the AI Headshot Generator are designed to be suitable for professional use. They can be used on LinkedIn profiles, business cards, company websites, and other professional platforms where a polished image is required.'
  },
  {
    q: 'Are there any limitations to the free version of the AI Headshot Generator?',
    a: 'While the free version of the AI Headshot Generator allows you to create professional headshots, there may be limitations such as a lower resolution output, fewer editing options, or a limit on the number of photos you can process. Upgrading to a paid version may offer additional features and higher quality outputs.'
  }
]

export default function PricingSection() {
  const [actIndex, steActIndex] = useState<number>(-1);

  const changeAct = (index: number) => {
    if (index === actIndex) {
      steActIndex(-1);
    } else {
      steActIndex(index);
    }
  }

  return (
    <div className="w-full max-w-4xl mb-16 p-8 rounded-lg">
      <h2 className="text-3xl font-bold text-center">FAQs About AI Headshot Generator Free</h2>
      <p className="text-sm text-center text-gray-500 mt-4 mb-16">Answers to common questions about our free AI generated headshot maker.</p>
      <div className="w-full grid grid-cols-2 gap-8">
        {
          QuestionList.map((item, index) => {
            return <div key={index} className="border-b border-gray-200 w-full pb-4" onClick={() => changeAct(index)}>
              <h4>
                <button className="flex w-full items-center justify-between text-left text-base font-bold text-gray-900">
                  <span>
                    {item.q}
                  </span>
                  <span aria-hidden="true" className={actIndex === index ? 'ml-4 rotate-45' : 'ml-4'}>
                    <Plus />
                  </span>
                </button>
              </h4>
              {
                actIndex === index && <div>
                  <div className="space-y-5 pt-4 transition-all">
                    <p className="text-base font-normal text-gray-900">
                      {item.a}
                    </p>
                  </div>
                </div>
              }
            </div>
          })
        }
      </div>
    </div>
  );
}
